theme: jekyll-theme-cayman
# Setup
title:        Questionable Research Labs
tagline:      QRL Tagline here
description:  A short description of your site's purpose
show_downloads: false
baseurl:      "/"
paginate:     1
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
