theme: jekyll-theme-cayman
# Setup
title: Questionable Research Labs
short: QRL
tagline: A space to play
description: An idea incubator for experiments in science and tech
show_downloads: false
baseurl: "/"
url: "https://questionable.org.nz"
locale: "en"

permalink: /:categories/:title/

# Projects folder is mapped to a collection
collections:
  projects:
    output: true
  info:
    output: true
  groups:
    output: true
  notices:
    output: true

# Gems/Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown

# Github Repo
repository: henry/henrydf.github.io

sass:
  style: compressed

exclude:
  - project-compressor/
