theme: jekyll-theme-cayman
# Setup
title:        Questionable Research Labs
short:        QRL
tagline:      QRL Tagline here
description:  A short description of your site's purpose
show_downloads: false
baseurl:      "/"
paginate:     1
locale:       "en"


permalink: /:categories/:title/

# Projects folder is mapped to a collection
collections:
  projects:
    output: true
  info:
    output: true

# Gems/Plugins
plugins:
  - jekyll-paginate

#Others
markdown: kramdown

# Github Repo
repository: henry/henrydf.github.io