# Setup
theme: jekyll-theme-cayman
show_downloads: false
baseurl: "/"
url: "https://questionable.org.nz"
locale: "en"
permalink: /:categories/:title/

# Site Info
title: Questionable Research Labs
short: QRL
tagline: A space to play
description: An idea incubator for experiments in science and tech

# Projects folder is mapped to a collection
collections:
  projects:
    output: true
  info:
    output: true
  groups:
    output: true
  notices:
    output: true

# Gems/Plugins
plugins:
  - jekyll-sitemap

#Markdown
markdown: kramdown

# Github Repo
repository: Questionable-Research-Labs/QRL-Website

sass:
  style: compressed
  sass_dir: assets/css/

exclude:
  - project-compressor/
